### ISSUE TITLE
i successfully froze kaa using pyinstaller !!!

### ISSUE THREAD

**Issue by berrytsakala** [kaaedit/kaa#135]
this is not a bug, but a success story
I managed to get a standalone "static" kaa executable file.

there were 2 bugs in pyinstaller (or rather, bugs in pyjf3 module?). 
I described them and my solution here: https://github.com/pyinstaller/pyinstaller/issues/1854
My solution is much simpler than recompiling python :\  ...

**Comment by atsuoishimoto** [comment]
Thank you for the info. 

pyjf3 contains non-unicode characters for testing. I should convert such files to be generated while testing on the fly.

**Comment by atsuoishimoto** [comment]
Filed the issue to pyjf3 repo. https://github.com/atsuoishimoto/pyjf3/issues/2
